/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.upeu.app.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import pe.edu.upeu.app.dao.conx.Conn;
import pe.edu.upeu.app.modelo.UsuarioTO;
import pe.edu.upeu.app.util.UtilsX;

/**
 *
 * @author ACER ASPIRE
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    BufferedImage image;
    UtilsX obj = new UtilsX();
    static PreparedStatement ps;
    ResultSet rs = null;
    Connection connection = Conn.connectSQLite();

    public Login() {
        initComponents();
        this.setTitle("Login CRONOS SysCenterLife");
        try {
            image = ImageIO.read(obj.getFile("CronosGym.jpg"));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        this.setIconImage(image);
        this.setResizable(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(new Dimension(screenSize.width / 2, (screenSize.height - 36) / 2));
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        jLabel4.setIcon(new ImageIcon(image));
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The con tent of this method is always
     * regenerated by the Form Editor.
     */
    UsuarioTO uTO = new UsuarioTO();

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelBorder1 = new pe.edu.upeu.app.components.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        myButton1 = new pe.edu.upeu.app.components.MyButton();
        jLabel2 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtclave = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBorder1.setBackground(new java.awt.Color(69, 97, 86));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panelBorder1.add(jLabel1);
        jLabel1.setBounds(60, 40, 80, 30);

        myButton1.setText("Ingresar");
        myButton1.setColor(new java.awt.Color(153, 255, 255));
        myButton1.setColorOver(new java.awt.Color(204, 255, 255));
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        panelBorder1.add(myButton1);
        myButton1.setBounds(30, 210, 120, 20);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        panelBorder1.add(jLabel2);
        jLabel2.setBounds(30, 90, 130, 16);

        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        panelBorder1.add(txtuser);
        txtuser.setBounds(30, 110, 100, 20);

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña");
        panelBorder1.add(jLabel3);
        jLabel3.setBounds(30, 140, 100, 16);

        txtclave.setText("jPasswordField1");
        panelBorder1.add(txtclave);
        txtclave.setBounds(30, 160, 100, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lol.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        panelBorder1.add(jLabel6);
        jLabel6.setBounds(0, 0, 190, 290);

        jPanel1.add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 289));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alt.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel4KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 710, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 780, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        String uname = txtuser.getText();
        String pword = txtclave.getText();
        if (uname.equals("") || pword.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ocurrio un error", "UPS¡", 1);

        } else {
            try {
                connection = Conn.connectSQLite();
                ps = connection.prepareStatement("SELECT * FROM usuario WHERE user=? and clave=?");

                ps.setString(1, uname);
                ps.setString(2, pword);
                rs = ps.executeQuery();

                if (rs.next()) {
                    GUIMain guiMain = new GUIMain();
                    guiMain.setVisible(true);
                    this.dispose();
                }

            } catch (Exception ex) {
                System.out.println("" + ex);
            }
        }
    }//GEN-LAST:event_myButton1ActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void jLabel4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4KeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private pe.edu.upeu.app.components.MyButton myButton1;
    private pe.edu.upeu.app.components.PanelBorder panelBorder1;
    private javax.swing.JPasswordField txtclave;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
