/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.upeu.app.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import pe.edu.upeu.app.dao.conx.Conn;
import pe.edu.upeu.app.modelo.UsuarioTO;
import pe.edu.upeu.app.util.UtilsX;

/**
 *
 * @author ACER ASPIRE
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    BufferedImage image;
    UtilsX obj = new UtilsX();
    static PreparedStatement ps;
    ResultSet rs = null;
    Connection connection = Conn.connectSQLite();

    public Login() {
        initComponents();
        this.setTitle("Login CRONOS SysCenterLife");
        try {
            image = ImageIO.read(obj.getFile("Angel.png"));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        this.setIconImage(image);
        this.setResizable(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(new Dimension(screenSize.width / 2, (screenSize.height - 36) / 2));
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        jLabel4.setIcon(new ImageIcon(image));
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The con tent of this method is always
     * regenerated by the Form Editor.
     */
    UsuarioTO uTO = new UsuarioTO();

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        myButton1 = new pe.edu.upeu.app.components.MyButton();
        txtclave = new javax.swing.JPasswordField();
        txtuser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 3, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LOGIN");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 180, 70));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 120, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("User:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 90, 30));

        myButton1.setBackground(new java.awt.Color(0, 51, 51));
        myButton1.setForeground(new java.awt.Color(255, 255, 255));
        myButton1.setText("Ingresar");
        myButton1.setColor(new java.awt.Color(153, 255, 255));
        myButton1.setColorOver(new java.awt.Color(204, 255, 255));
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 100, 30));

        txtclave.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        getContentPane().add(txtclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 130, 20));

        txtuser.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 130, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Angel.png"))); // NOI18N
        jLabel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel4KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, 0, 720, 490));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo negro.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, -10, 600, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        String uname = txtuser.getText();
        String pword = txtclave.getText();
        if (uname.equals("") || pword.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ocurrio un error", "UPS¡", 1);

        } else {
            try {
                connection = Conn.connectSQLite();
                ps = connection.prepareStatement("SELECT * FROM usuario WHERE user=? and clave=?");

                ps.setString(1, uname);
                ps.setString(2, pword);
                rs = ps.executeQuery();

                if (rs.next()) {
                    GUIMain guiMain = new GUIMain();
                    guiMain.setVisible(true);
                    this.dispose();
                }

            } catch (Exception ex) {
                System.out.println("" + ex);
            }
        }
    }//GEN-LAST:event_myButton1ActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void jLabel4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4KeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private pe.edu.upeu.app.components.MyButton myButton1;
    private javax.swing.JPasswordField txtclave;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
